options:
  port:
    type: int
    default: 8000
    description: |
      "API port for Burrow"
  consumer-groups:
    type: string
    default: ".*"
    description: |
      "Space separated list of consumer groups used by notifiers. Defaults to all consumer groups."